# Generated by Django 5.1 on 2024-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="remaining_leave",
            field=models.IntegerField(default=10),
        ),
    ]
