# Generated by Django 5.1 on 2024-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_leave_remaining_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
