# Generated by Django 5.1 on 2024-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0003_leave_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
