# Generated by Django 5.1 on 2024-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employe", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("position", models.CharField(max_length=100)),
                ("joining_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
            ],
        ),
    ]
