# Generated by Django 5.1 on 2024-10-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employe", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
