# Generated by Django 5.1 on 2024-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leavebalance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="LeaveBalance",
        ),
        migrations.DeleteModel(
            name="LeaveRequest",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
