# Generated by Django 5.1 on 2024-10-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_userprofile_employee_id_alter_userprofile_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="position",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("ui/ux", "UI/UX Designer"),
                    ("manager", "Manager"),
                    ("analyst", "Analyst"),
                ],
                default="developer",
                max_length=100,
            ),
        ),
    ]
