# Generated by Django 5.1 on 2024-10-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_userprofile_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(default="default.png", upload_to="profile_pics/"),
        ),
    ]
