# Generated by Django 5.1 on 2024-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
    ]
