# Generated by Django 5.1 on 2024-10-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
