# Generated by Django 5.1 on 2024-10-16 07:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="events",
            name="created_by",
        ),
        migrations.AddField(
            model_name="events",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="events",
            name="time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
