# Generated by Django 5.1 on 2024-10-17 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_alter_events_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
