# Generated by Django 5.1 on 2024-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0004_alter_events_category_alter_events_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
